init -999 python:

    CN_REPLACE = {
        #人名
        "Lisa": "丽莎",
        "Rose": "罗丝",
        "Abigail": "阿比盖尔",
        "Amber": "安珀",
        "Amber and Jade":"安珀和杰德",
        "Jade": "杰德",
        "Aqua": "阿库娅",
        "Astra": "阿斯特拉",
        "Aurora": "奥罗拉",
        "Ava": "艾娃",
        "Chloe": "克洛伊",
        "Cynthia": "辛西娅",
        "RaccoonGirl": "浣熊女孩",
        "Daisy": "黛西",
        "Diana": "戴安娜",
        "Ellie": "艾莉",
        "Kaia": "凯亚",
        "Emily": "艾米莉",
        "Emma": "艾玛",
        "Freya": "芙蕾雅",
        "Hannah": "汉娜",
        "Liv": "莉芙",
        "Helen": "海伦",
        "Luna":"露娜",
        "Iris": "艾瑞斯",
        "Ivy": "艾薇",
        "Jenny": "珍妮",
        "Julia": "朱莉娅",
        "Katherine": "凯瑟琳",
        "Kora": "科拉",
        "Layla": "蕾拉",
        "Leah": "莉亚",
        "Lily": "莉莉",
        "Lucy": "露西",
        "Megan": "梅根",
        "Mia": "米娅",
        "Nadia": "纳迪亚",
        "Naomi": "娜奥米",
        "Nora": "诺拉",
        "Nova": "诺娃",
        "Think": "思思",
        "Quila": "奎拉",
        "Jill": "吉尔",
        "Roxie": "罗克茜",
        "Sally": "莎莉",
        "Sarah": "莎拉",
        "Katie": "凯蒂",
        "Lana": "拉娜",
        "Selene": "塞勒涅",
        "Sophia": "索菲娅",
        "Talia": "塔莉亚",
        "Tara": "塔拉",
        "Valerie": "瓦莱丽",
        "Zoe": "佐伊",
        "Silas": "塞拉斯",
        #日期
        "Any morning": "任何早上",
        "Any Night": "任何晚上",
        "Any Afternoon/Night": "任何下午/晚上",
        "Mon-Fri morning": "周一至周五早上",
        "Weekday Night": "工作日晚上",
        "Any Afternoon": "任何下午",
        "Friday/Saturday Night": "周五/周六晚上",
        "Saturday Morning": "周六早上",
        "Saturday Afternoon": "周六下午",
        "Monday": "星期一",
        "Tuesday": "星期二",
        "Wednesday": "星期三",
        "Thursday": "星期四",
        "Friday": "星期五",
        "Saturday": "星期六",
        "Sunday": "星期日",
        "Morning": "早上",
        "Afternoon": "下午",
        "Night": "晚上",
        #其他
        "Press ENTER to use the default title":"回车使用默认称呼",
        "(Pregnancy)":"（怀孕）",
        "Unknown":"未知", 
        "Human":"人类",
        "Wolf":"狼",
        "Cow":"牛",
        "Celestial": "天族",
        "Height:": "身高：",
        "Age:": "年龄：",
        "Cup Size:": "罩杯：",
        "Race:": "种族：",
        "Tamed:": "驯服：",
        "Kissed:": "接吻：",
        "Handjob:": "手交：",
        "Blowjob:": "口交：",
        "Boobjob:": "乳交：",
        "Sex:": "性爱：",
        "Anal:": "肛交：",
        "Strength":"力量",
        "Intelligence":"智力",
        "Magic":"魔法",
        "Charisma":"魅力",
        "Endurance":"魔力",
        "There's currently no available side girl hints. Progress the story or main girls' hints further to unlock more.": "目前没有可用的配角提示。需要继续推进剧情或了解主要角色的更多信息，才能解锁更多内容。",
        #地址
        "Market":"市场",
        "Guest room": "客房",
        "Forest": "森林",
        "Nest": "巢穴",
        "Ruins": "废墟",
        "Backyard": "后院",
        "Bedroom": "卧室",
        "East hall": "东厅",
        "Kitchen": "厨房",
        "Emily room": "艾米莉的房间",
        "Ellie room":"艾莉的房间",
        "Living room": "客厅",
        "West hall": "西厅",
        "Apartments": "公寓",
        "Bar": "酒吧",
        "Beach": "海滩",
        "Church": "教堂",
        "Club": "俱乐部",
        "Company": "公司",
        "Farm": "农场",
        "Fox village": "狐狸村",
        "Island": "岛屿",
        "Office": "办公室",
        "Park": "公园",
        "Police": "警察局",
        "Restaurant": "餐厅",
        "Slums": "贫民窟",
        "Station": "车站",
        "Bathroom": "浴室",
        "Lisa room": "丽莎的房间",
        "Witch shop": "女巫商店",
        "Apartments second": "公寓二楼",
        "Apartments third": "公寓三楼",
        "Bar house": "酒吧屋",
        "Rose room": "罗斯的房间",
        "Company reception": "公司前台",
        "Gym": "健身房",
        "Attic": "阁楼",
        "Stranded": "搁浅地",
        "Freya house": "芙蕾雅的家",
        "Layla house": "蕾拉的家",
        "Apartments first": "公寓一楼",
        "Gang hideout": "帮派藏身处",
        "Apartments fourth": "公寓四楼",
        "Away": "外出",
        "General store": "杂货店",
        "Elders house": "长老的家", 
        "Helen house": "海伦的家",
        "Abigail house": "阿比盖尔的家",
        "Tavern": "酒馆",
        # name.rpy 中原有、但 CN_REPLACE 尚未收录的内容
        "Bunny Bartender": "兔酒保",
        "Bunny Bartender 2": "兔酒保2",
        "Detective": "侦探",
        "Receptionist": "接待员",
        "Farmer": "农场主人",
        "Raccoon Girl": "浣熊女孩",
        "Sophia(Boss)": "索菲娅(老板)",
        "Mr. Adams": "亚当斯先生",
        "Mrs. Adams": "亚当斯夫人",
        "cow2": "奶牛女孩2",
        "Rose's Family Friend": "[Rose]的家庭朋友",
        "Scientist": "科学家",
        "CowGirl": "奶牛女孩",
        "Wolf Girl": "狼女孩",
        "Bird Girl": "鸟女孩",
        "Slime Girl": "史莱姆女孩",
        "Bear Girl": "熊女孩",
        "Bunny Girl": "兔女孩",
        "Elder 1": "长老1",
        "Elder 2": "长老2",
        "Elder 3": "长老3",
        "Old Lady": "老太太",
        "Enforcer 1": "打手1",
        "Enforcer 2": "打手2",
        "Enforcer 3": "打手3",
        "GangCaptain": "帮派队长",
        "Gang Member": "帮派成员",
        "GangUnderboss": "帮派二把手",
        "GangBoss": "帮派老大",
        "Amber abd jade": "安珀与杰德",
        "Waiter": "服务员",
        "Sam": "萨姆",
        "Breedable": "是否可繁育",
        "Visit": "拜访",
        # 星期缩写
        "Mon": "周一",
        "Tue": "周二",
        "Wed": "周三",
        "Thu": "周四",
        "Fri": "周五",
        "Sat": "周六",
        "Sun": "周日",
        # 月份
        "January": "一月",
        "February": "二月",
        "March": "三月",
        "April": "四月",
        "May": "五月",
        "June": "六月",
        "July": "七月",
        "August": "八月",
        "September": "九月",
        "October": "十月",
        "November": "十一月",
        "December": "十二月",
        "Jan": "1月",
        "Feb": "2月",
        "Mar": "3月",
        "Apr": "4月",
        "Jun": "6月",
        "Jul": "7月",
        "Aug": "8月",
        "Sep": "9月",
        "Oct": "10月",
        "Nov": "11月",
        "Dec": "12月",
        "back": "返回",
    }